name: debernardo
description: Sincronização de postagens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  logger: ^2.0.2+1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.6
  uuid: ^4.3.3
  flutter_html: 3.0.0-beta.2
  flutter_math_fork: 0.7.2
  flutter_staggered_grid_view: ^0.4.1
  image_picker: ^0.8.4+4
  path: ^1.8.3
  video_player: ^2.8.3
  chewie: ^1.6.0
  mime: ^1.0.5
  url_launcher: ^6.2.5
  flutter_cache_manager: ^3.3.1
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  xml: ^6.1.0
  i18n_extension: ^9.0.2
  zefyrka: ^1.6.0
  html: ^0.15.4
  notus: ^1.0.0-rc.2
  flutter_datetime_picker: ^1.5.1
  flutter_quill: ^9.3.3
  shared_preferences: ^2.2.2
  provider: ^6.0.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/mipmap.svg